version: '3.7'

services:
  pg_db:
    image: postgres
    restart: always
    container_name: pg_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-pwd}
      - POSTGRES_USER=${POSTGRES_USER-admin}
      - POSTGRES_DB=${POSTGRES_DB-testdb}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
    name: backend
    driver: bridge
